services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ais
    volumes:
      - "./home/nikhil-james/Workspace/Data-Engineering-Refresher/Week_2/ais_pg:/var/lib/postgresql/data"
    ports:
      - "5431:5432"
    networks:
      - week-2_884d23_airflow  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root 
    ports:
      - "8081:80"
    networks:
      - week-2_884d23_airflow 

networks:
  week-2_884d23_airflow:
    driver: bridge